export const STAGES = [
  {
    id: 1,
    name: { de: "Stufe 1", en: "Stage 1" },
    target: {
      power: true,
      phase: false,
      freq: 34,
      fine: -8,
      gain: 42,
      colorR: 0,
      colorG: 0,
      colorB: 0,
      routes: [],
    },
    tolerance: { freq: 16, fine: 18, gain: 18, colorR: 255, colorG: 255, colorB: 255 },
    message: {
      de: "DOOMSDAY RADIO GEFUNDEN, EMPFANG NOCH ZERRISSEN. EINE FREQUENZ HAELT SCHON, DOCH DIE STACK-SIGNALSTOERUNG FRISST FAST JEDEN SATZ AN. HALTE DIE GRUNDLINIE RUHIG, DANN WIRD DAS PROGRAMM HOERBAR.",
      en: "DOOMSDAY RADIO DETECTED, RECEPTION STILL TORN APART. ONE FREQUENCY HOLDS, BUT THE STACK SIGNAL INTERFERENCE EATS MOST OF THE SENTENCE. STEADY THE BASELINE AND THE PROGRAM WILL START TO COME THROUGH.",
    },
    briefing: {
      de: "Stufe 1: Grundabgleich. Farbcode und Patchfeld sind deaktiviert. Halte Strom, Phase und die drei Regler so sauber, dass du die Grundfrequenz von Doomsday Radio festhalten kannst.",
      en: "Stage 1: Basic alignment. Color Code and patch panel are disabled. Keep power, phase, and the three knobs steady enough to hold the base frequency of Doomsday Radio.",
    },
    codeword: { de: "FREQUENZ", en: "FREQUENCY" },
  },
  {
    id: 2,
    name: { de: "Stufe 2", en: "Stage 2" },
    target: {
      power: true,
      phase: true,
      freq: 59,
      fine: 13,
      gain: 67,
      colorR: 64,
      colorG: 176,
      colorB: 96,
      routes: [],
    },
    tolerance: { freq: 13, fine: 14, gain: 14, colorR: 72, colorG: 72, colorB: 72 },
    message: {
      de: "DIE TRAEGERSPUR VON DOOMSDAY RADIO HAELT. HINTER DEN FARBVERSCHIEBUNGEN LAEUFT BEREITS DAS NACHTPROGRAMM, ABER DIE STACK-LAGEN ZIEHEN DEN TON NOCH AUSEINANDER. GLEICHE DIE KANAELE AN, DAMIT DIE STIMME NICHT WEGKIPPT.",
      en: "THE DOOMSDAY RADIO CARRIER HOLDS. BEHIND THE COLOR SHIFT THE NIGHT PROGRAM IS ALREADY RUNNING, BUT THE STACK LAYERS STILL PULL THE AUDIO APART. BALANCE THE CHANNELS SO THE VOICE STOPS SLIPPING.",
    },
    briefing: {
      de: "Stufe 2: Die Stack-St\u00f6rung zeigt sich jetzt als Farbschleier. Das Patchfeld bleibt gesperrt. Nutze die drei Farbkan\u00e4le, um die Traegerspur von Doomsday Radio sauber auszubalancieren.",
      en: "Stage 2: The Stack interference now appears as a color veil. The patch panel stays locked. Use the three color channels to balance the Doomsday Radio carrier cleanly.",
    },
    codeword: { de: "TRAEGERSPUR", en: "CARRIER" },
  },
  {
    id: 3,
    name: { de: "Stufe 3", en: "Stage 3" },
    target: {
      power: true,
      phase: true,
      freq: 72,
      fine: -19,
      gain: 58,
      colorR: 196,
      colorG: 96,
      colorB: 40,
      routes: ["PRE->FLT"],
    },
    tolerance: { freq: 10, fine: 11, gain: 11, colorR: 52, colorG: 52, colorB: 52 },
    message: {
      de: "DIE STACK-STOERUNG LIEGT OFFEN. EIN FALSCHES KABEL FUETTERT DAS ECHO, DIE RICHTIGE ROUTE SCHNEIDET DEN MUELL AB. DOOMSDAY RADIO IST DIREKT DAHINTER, NOCH BRUCHSTUECKHAFT, ABER KLAR GENUG FUER EINEN ERSTEN STACK-MARKER.",
      en: "THE STACK INTERFERENCE IS EXPOSED. ONE WRONG CABLE FEEDS THE ECHO, THE RIGHT ROUTE CUTS THE TRASH AWAY. DOOMSDAY RADIO SITS RIGHT BEHIND IT, STILL FRAGMENTED, BUT CLEAR ENOUGH FOR A FIRST STACK MARKER.",
    },
    briefing: {
      de: "Stufe 3: Das Patchfeld ist frei, aber auf ein Kabel begrenzt. Suche die eine Verbindung, die die Stack-Signalst\u00f6rung umgeht, statt sie weiter im Kreis zu schicken.",
      en: "Stage 3: Patching is unlocked, but limited to one cable. Find the one route that bypasses the Stack signal interference instead of feeding it back into the loop.",
    },
    codeword: { de: "STACK", en: "STACK" },
  },
  {
    id: 4,
    name: { de: "Stufe 4", en: "Stage 4" },
    target: {
      power: true,
      phase: false,
      freq: 16,
      fine: 24,
      gain: 76,
      colorR: 32,
      colorG: 156,
      colorB: 224,
      routes: ["ANT->FLT", "FLT->DEC"],
    },
    tolerance: { freq: 9, fine: 9, gain: 10, colorR: 38, colorG: 38, colorB: 38 },
    message: {
      de: "DIE SENDESIGNATUR BLEIBT FAST STEHEN. MODERATION, JINGLE UND NOTFALLBLOCK SCHIEBEN SICH BEREITS NACH VORN, WENN DIE STOERFARBEN SAUBER LIEGEN. HALTE DIE ROUTEN RUHIG, DANN BRICHT DIE SIGNATUR NICHT WIEDER WEG.",
      en: "THE BROADCAST SIGNATURE IS ALMOST STABLE. HOST VOICE, JINGLE, AND EMERGENCY BLOCK ARE ALREADY MOVING FORWARD WHEN THE INTERFERENCE COLORS LINE UP. KEEP THE ROUTES CALM SO THE SIGNATURE DOES NOT COLLAPSE AGAIN.",
    },
    briefing: {
      de: "Stufe 4: Volle Kontrolle aktiv. Farbcode und Patchfeld sind komplett freigegeben. Kombiniere mehrere Kabel mit einer sauberen Farb-Balance, damit die Sendesignatur von Doomsday Radio durch den Stack dringt.",
      en: "Stage 4: Full control unlocked. Color Code and patch panel are fully available. Combine multiple cables with clean color balance so the Doomsday Radio broadcast signature can cut through the Stack.",
    },
    codeword: { de: "SIGNATUR", en: "SIGNATURE" },
  },
  {
    id: 5,
    name: { de: "Stufe 5", en: "Stage 5" },
    target: {
      power: true,
      phase: true,
      freq: 47,
      fine: 3,
      gain: 51,
      colorR: 224,
      colorG: 48,
      colorB: 168,
      routes: ["ANT->PRE", "PRE->FLT", "FLT->DEC", "DEC->ANT"],
    },
    tolerance: { freq: 7, fine: 7, gain: 8, colorR: 26, colorG: 26, colorB: 26 },
    message: {
      de: "DAS PROGRAMM IST FREI. DOOMSDAY RADIO KOMMT ENDLICH DURCH DEN STACK, DIE STIMMEN SIND STABIL UND DER AETHER HAELT. LETZTE FEINARBEIT: JEDER FEHLER DRUECKT DAS PROGRAMM SOFORT WIEDER ZURUECK INS RAUSCHEN.",
      en: "THE PROGRAM IS CLEAR. DOOMSDAY RADIO FINALLY CUTS THROUGH THE STACK, THE VOICES HOLD STEADY, AND THE AIR STAYS OPEN. FINAL PRECISION NOW: EVERY MISTAKE PUSHES THE PROGRAM STRAIGHT BACK INTO THE NOISE.",
    },
    briefing: {
      de: "Stufe 5: Endphase. Alle Werkzeuge sind aktiv und die Toleranzen sind eng. Umgehe die Stack-Signalst\u00f6rung vollst\u00e4ndig, damit das komplette Programm von Doomsday Radio h\u00f6rbar bleibt.",
      en: "Stage 5: Final phase. All tools are active and tolerances are tight. Bypass the Stack signal interference completely so the full Doomsday Radio program stays audible.",
    },
    codeword: { de: "PROGRAMM", en: "PROGRAM" },
  },
];
